### ISSUE TITLE
Problem with factor by fit in 2021-3-27 post

### ISSUE THREAD

**Issue by gavinsimpson** [cbrown5/cbrown5.github.io#4]
In [your 2021-3-27 post](https://github.com/cbrown5/cbrown5.github.io/blob/e369b3277e9740b28702a0bcd46b81736e59f709/_posts/2021-03-27-common-GAM-problems.md) there is a problem in `fit2` here https://github.com/cbrown5/cbrown5.github.io/blob/e369b3277e9740b28702a0bcd46b81736e59f709/_posts/2021-03-27-common-GAM-problems.md?plain=1#L212 and here https://github.com/cbrown5/cbrown5.github.io/blob/e369b3277e9740b28702a0bcd46b81736e59f709/_posts/2021-03-27-common-GAM-problems.md?plain=1#L221 

The model needs to include the factor variable `grp2` as a parametric effect

```r
fit2 <- gam(y ~ grp2 + s(x, by = grp2), data = dat) 
```

And the `visreg()` call is referencing `fit1` instead of `fit2` https://github.com/cbrown5/cbrown5.github.io/blob/e369b3277e9740b28702a0bcd46b81736e59f709/_posts/2021-03-27-common-GAM-problems.md?plain=1#L222-L224 

which is why it looks like the model worked ok

**Comment by cbrown5** [comment]
Thanks Gavin really appreciate the corrections. I fixed this and sorry I never saw this message! Just found it now when I was working on a new GAM post. Obviously need to do something about my github notifications.
